### ISSUE TITLE
ReactRouterSSR and loadwebpackinfos

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-simple#10]
Thanks for this great package!
Yhis is only a noob question: what is ReactRouterSSR.LoadWebpackStats good for?
I am using CSR, so not sure if I can remove this.

Thanks.

**Comment by eXon** [comment]
Yes you can remove this, it has no impact. This file is mainly for code splitting and SSR. It adds the code splitting scripts to SSR when visiting the section directly. It has no purpose if you're not doing SSR.

**Comment by tomitrescak** [comment]
So code splitting won't work with csr.? Shame;(
On Thu, Oct 15, 2015 at 8:13 PM, Benoit Tremblay <notifications@github.com>
wrote:

> Yes you can remove this, it has no impact. This file is mainly for code
> splitting and SSR. It adds the code splitting scripts to SSR when visiting
> the section directly. It has no purpose if you're not doing SSR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/thereactivestack/kickstart-simple/issues/10#issuecomment-148326852>
> .
>
-- 
~
Tomi Trescak / Researcher  tomi.trescak@gmail.com / 0487 261 213

**Comment by eXon** [comment]
@tomitrescak No it will work. But when you do SSR, you have to include the .js you splitted for the first render to be the same. It is purely a SSR problem but it will work without it with CSR.
