### ISSUE TITLE
Error: EACCES, mkdir '~/.meteor

### ISSUE THREAD

**Issue by imkost** [thereactivestack/kickstart-simple#11]
0) I use OS X El Capitan
1) `git clone https://github.com/thereactivestack/kickstart-simple.git ~/Projects/kickstart`
2) `cd ~/Projects/kickstart`
3) `meteor`
4) I get this:
![image](https://cloud.githubusercontent.com/assets/2445890/10526294/9ceced8c-7392-11e5-9fd2-7e5ba52d1c02.png)

I understand that there is some problem with user rights, but I don't understand what is exactly wrong.

How I fix this issue:
1. run meteor with sudo 
OR
2. `chmod -R 777 ~/.meteor`

`~` is an alias for `/Users/imkost`

**Comment by eXon** [comment]
This is weird. Can you run other projects with Meteor? Have you tried removing ~/.meteor/packages/webpack_webpack and build again without sudo?

**Comment by imkost** [comment]
Thanks! The problem was because webpack_webpack was created by sudo (I don't remember why, but I run kickstart as sudo for the first time). I just reinstalled Meteor and run kickstart again — no errors. Nice!
