### ISSUE TITLE
_Mongo is not defined in production mode

### ISSUE THREAD

**Issue by imkost** [thereactivestack/kickstart-simple#12]
When I run kickstart in production mode (`NODE_ENV=production meteor run --production`), I get this error:

![image](https://cloud.githubusercontent.com/assets/2445890/10529672/9a32ea68-73a8-11e5-8718-b0a82d3f154f.png)

Seems like Mongo is not working for production.

**Comment by eXon** [comment]
Damnit, this is dumb to fix I'm publishing it as soon as I get home. My mistake.

**Comment by eXon** [comment]
This is fixed

**Comment by imkost** [comment]
Thank you!
