### ISSUE TITLE
"Symbol is not defined" for server-rendering

### ISSUE THREAD

**Issue by imkost** [thereactivestack/kickstart-simple#13]
I have this code inside my component:

```js
for (const item of items) {
  // do something
}
```

This code is transformed to this code by babel:

```javascript
"use strict";

var _iteratorNormalCompletion = true;
var _didIteratorError = false;
var _iteratorError = undefined;

try {
  for (var _iterator = items[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
    var item = _step.value;
  }
} catch (err) {
  _didIteratorError = true;
  _iteratorError = err;
} finally {
  try {
    if (!_iteratorNormalCompletion && _iterator["return"]) {
      _iterator["return"]();
    }
  } finally {
    if (_didIteratorError) {
      throw _iteratorError;
    }
  }
}
```

As you see, `Symbol` is used. `Symbol` is defined for client, but seems like it is not defined for server (or just for server-side rendering)

![image](https://cloud.githubusercontent.com/assets/2445890/10552136/5f491d3e-745a-11e5-8593-02b99ff05681.png)

**Comment by eXon** [comment]
Meteor is running on a old version of Node.js. I'll add the babel polyfill for this.

**Comment by eXon** [comment]
I've added babel/polyfill to the project

**Comment by imkost** [comment]
Thank you! You close issues so fast. You are reactive )

**Comment by eXon** [comment]
Haha thx, i'm planning on doing tutorials on this but i want it to be perfect first :). Always appreciated to have people like you reporting bugs and asking for cool features.
