### ISSUE TITLE
Meteor-Webpack for dummies

### ISSUE THREAD

**Issue by SenerDemiral** [thereactivestack/kickstart-simple#14]
Thank you for your great work!

I can't connect things!
Why do not you write "Meteor-Webpack for dummies"?

Who is the maestro? Meteor/Webpack.
What happens when "meteor run"?
Who does What and Why and When?
....

**Comment by eXon** [comment]
It is coming soon, probably in a week or two. Tutorials are on their way :)

**Comment by SenerDemiral** [comment]
Perfect.
