### ISSUE TITLE
[feature-request] declare dependencies to a 'module'

### ISSUE THREAD

**Issue by garrilla** [thereactivestack/kickstart-simple#16]
it would be great if there was some way to declare dependencies to a 'module' under this structure.

The new modular structure does make more sense. I've just pulled in a app from the original none-modular version of KSS, into the current version and it took some effort - so I can see the value of the modular structure. However, I still had to do some work on dependencies, adding smart packages to to `.meteor/packages` and npm packages to `./packages.json`.

Also, I had to add a loader for scss, if it was possible declare loaders too it would be useful.

Hopefully, this makes sense. If not, please ask for clarification.

**Comment by eXon** [comment]
I'm not sure what the feature request is. Can you give me a concrete example?

**Comment by garrilla** [comment]
So, in your example app you have the ToDoApp module. Let's say I add BlogApp module. 

BlogApp has dependencies: packages, NPMs, loaders.

Copying the BlogApp directory from one project to another is trivial, but not its dependencies. Unless a good record is made of this its easy to forget what should also be added to the project (I started using BlogApp/.deps/deps.json* as an aid memoir after I posted this issue)

It would be useful to automate this some how, at build stage, maybe by looking for some json structure and merge it into the project's structure at the appropriate places... I suppose this would make them smart modules...

All that's left for me to do is then integrate BlogApp into the entry system and wider app...

* example deps.json
```js
{
  packages: [
    "check", "reactive-var", "email", "kenlimj:hljs", "and:so-on"
  ]
  npm: {
    "sass-loader": "3.0.0",
    "react-intl" : "1.2.0",
    "react-remarkable": "1.1.1"
  },
  loaders: {
    scss:  { test: /\.scss$/, loader: 'style!css!sass' }
  },
  extensions: [
    '.scss'
  ]
}
{
  packages: [
    "check", "reactive-var", "email", "kenlimj:hljs", "and:so-on"
  ]
  npm: {
    "sass-loader": "3.0.0",
    "react-intl" : "1.2.0",
    "react-wysiwyg": "2.1.7",
    "react-remarkable": "1.1.1"
  },
  loaders: {
    scss:  { test: /\.scss$/, loader: 'style!css!sass' }
  },
  extensions: [
    '.scss'
  ]
}
```

**Comment by eXon** [comment]
You could have all your NPM dependencies in BlogApp/webpack.packages.json. For the rest, I'm not so sure you don't usually setup a ton of loaders.

I'm not a big fan of changing too much the webpack config structure. I personally tend to keep it light and simple. Some loaders vary from project to project but that's it..
