### ISSUE TITLE
Changes do not get pushed as hot replaces on Windows

### ISSUE THREAD

**Issue by jdanilov** [thereactivestack/kickstart-simple#17]
Hi! I'm having a problem on Windows getting the code changes pushed as hot replaces. Changes only applied if I wait for ~30s after the previous file save. Here is a console output:

```
[HMR] connected
client.js?3997:106 [HMR] bundle rebuilding
client.js?3997:108 [HMR] bundle rebuilt in 1117ms
process-update.js?e8cb:25 [HMR] Checking for updates on the server...
index.js?6622:81 [React Transform HMR] Patching TodoMain
process-update.js?e8cb:75 [HMR] Updated modules:
process-update.js?e8cb:77 [HMR]  - D:/ws/kickstart-simple/modules/TodoApp/client/TodoMain.jsx
process-update.js?e8cb:82 [HMR] App is up to date.
client.js?3997:106 [HMR] bundle rebuilding
client.js?3997:108 [HMR] bundle rebuilt in 909ms
client.js?3997:106 [HMR] bundle rebuilding
client.js?3997:108 [HMR] bundle rebuilt in 1221ms
client.js?3997:106 [HMR] bundle rebuilding
client.js?3997:108 [HMR] bundle rebuilt in 874ms
client.js?3997:106 [HMR] bundle rebuilding
client.js?3997:108 [HMR] bundle rebuilt in 1406ms
process-update.js?e8cb:25 [HMR] Checking for updates on the server...
index.js?6622:81 [React Transform HMR] Patching TodoMain
process-update.js?e8cb:75 [HMR] Updated modules:
process-update.js?e8cb:77 [HMR]  - D:/ws/kickstart-simple/modules/TodoApp/client/TodoMain.jsx
process-update.js?e8cb:82 [HMR] App is up to date.
```

Notice the initial change was applied then I made 3 changes and none of them got applied. I waited for a minute before making the 4th change which was then pushed successfully.

This issue kills productivity on a Windows to a point I can't use the kickstart. Works on Linux just fine. Please also note refreshing the page doesn't help as changes do not get hot pushed as replaces even after page refresh.

Any ideas or thoughts on how to resolve this are welcome.

**Comment by eXon** [comment]
I am well aware of the problem. I'm working on resolving this issue. It is totally unacceptable for the Windows user I agree.

**Comment by eXon** [comment]
This is fixed in the last version!!!!

Just make sure you are using path.join for your resolve.root in your webpack.conf.js :)

**Comment by jdanilov** [comment]
Excellent, I will give it a try!
