### ISSUE TITLE
velocity test not running

### ISSUE THREAD

**Issue by swemail** [thereactivestack/kickstart-simple#19]
I have the same setup and added tests to `modules/MyApp/tests/jasmine` but neither `meteor` or `meteor run --test` seems to execute any tests.

**Comment by eXon** [comment]
This is my next battle. It's coming :)

**Comment by eXon** [comment]
I just want to make sure to nail everything before the tests (sound like most of my projects at work LOL). Anyways, I want to get the testing right and I think it would make sense to also use Webpack for them. They need to be able to import files anyways. I'll keep this issue open for tracking.

**Comment by swemail** [comment]
Ok, good to know. See if I'll find some webpack way.

**Comment by eXon** [comment]
You can now use velocity with webpack! :) There is examples.
