### ISSUE TITLE
ReferenceError: Can't find variable: webpackJsonp

### ISSUE THREAD

**Issue by bearcanrun** [thereactivestack/kickstart-simple#2]
Meteor command runs fine and I get App running at: http://localhost:3000/ but in the browser I get 
ReferenceError: Can't find variable: webpackJsonp
in my error console. 

Tried doing quick google search for cause, but got vague solutions about load order. This is my first exposure to webpack, so maybe I'm missing someting basic.

Any ideas?

**Comment by eXon** [comment]
This is because common.web.js is not included before meteor javascript. Are you using a fresh clone and what command do you use to run meteor?

**Comment by bearcanrun** [comment]
I cloned just a little bit before my original post. I just used 'meteor' as the documentation stated.

**Comment by bearcanrun** [comment]
So I experimented with the meteor side of load order and moved webpack.conf.js to their respective client/server locations in deeper directories: ../vendor/webpack/lib/. Updated path to entry.js. Now webpack for sure loads first, and app is running at localhost: 3000

Now I get the errors: 
Error 404 http://localhost:3500/assets/web.js
Error 404 http://localhost:3500/assets/common.web.js

Node is operating on :3500 but "cannot /GET" 
I confess I've been using meteor a lot, but not familiarized myself with foundations, ie Node.

**Comment by eXon** [comment]
Webpack dev server is running on the 3500 port. This is only for development and give a much better development experience. I'm not sure why but it looks like it is not running. Do you have a git repo I can look into your project?

**Comment by bearcanrun** [comment]
I had a feeling this had to do with my environment since no one else seemed to be having the problem. So I installed webpack via npm globally (on Mac OSX 10.10.5), re-cloned your git, ran it, and now it works with no problems.
