### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-simple#21]
Hi, already ported quite large app to this webpack and is running quite well. Great job!
I have a small issue. I need to define some meta tags and favicon info but there is no global htmlfile in which I can define header info. Also I need to insert some extral javascripts from cdns. Would you please advise what is the best way to do this?

Thanks

**Comment by SenerDemiral** [comment]
https://github.com/thereactivestack/kickstart-flowrouter/issues/3

**Comment by eXon** [comment]
You can add a html file in any folder. If you don't use Blaze, you can even remove it and use static-html package only.

main.html:
```html
<head>
 <title>Kickstart Simple</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
</head>
```

**Comment by tomitrescak** [comment]
Thanks for the response! I don't use blaze at all. What do you mean by static hunk package. Sorry for a dumb question.

**Comment by eXon** [comment]
If you are not using blaze at all, since Meteor 1.2 you can remove the `blaze-html-templates` package and only use `static-html` template (for things like your header). That way Blaze doesn't even need to be loaded in your app :)
