### ISSUE TITLE
Cordova Performance

### ISSUE THREAD

**Issue by xDreamCoding** [thereactivestack/kickstart-simple#22]
So i got the vanilla kickstart-simple checked out.
Got it deployed with mup on my Ubuntu vserver and its working fine in browser.
Now i was testing the Cordova build with Crosswalk on Android and its working, but the app startup time is horrible.
It shows the meteor splashscreen (5-7 secs) then white screen (2-3 secs) then the actual app is displayed. Also pressing back button gets you to the white screen instead of closing the app.
I was wondering if that has to do with meteor or this stack or something different, because with the cordova example i got 1sec appsstart and immediate display of the app and it feels more like a native app.
Also didnt get the app to work on the production server, was testing on local server.

**Comment by eXon** [comment]
I haven't really tested performance on Cordova but it should not be different from regular Meteor app. We'll have to investigate more on that. Sorry I haven't much time to spend on this but any help would be appreciated.

**Comment by eXon** [comment]
I'm closing this for now but if you have anything helpful to solve this, let me know!
