### ISSUE TITLE
check() always throws error when checking for Number

### ISSUE THREAD

**Issue by coniel** [thereactivestack/kickstart-simple#23]
I added edge:slingshot to my project, and it was throwing an error: ```Error: Match error: Failed Match.OneOf or Match.Optional validation in field maxSize``` even though I had defined maxSize as a number.

So I did a test in a clean install of this repo by adding the ```check``` package and adding ```check(123, Number);``` into ```entry/server/entry.js``` and got the same result: ```Error: Match error: Expected Number```, even though 123 is clearly a number.

If I try ```check(123, String);``` it correctly throws an error: ```Error: Match error: Expected string, got number```. Everything works normally on the client (I did the same test in ```entry/client/entry.js```).

**Comment by tomitrescak** [comment]
I think it's the same issue a here thereactivestack/kickstart-simple#9

Probably has something to do with corejs ans I see it as a bug.

**Comment by eXon** [comment]
This seems to be a bug with check package. Are you having this error with a regular Meteor project without Webpack?

**Comment by coniel** [comment]
Nope, tried with a clean standard Meteor project and it works fine (I've also used ```edge:slingshot``` in all of my other projects and it worked fine).

**Comment by eXon** [comment]
I've removed the babel/polyfill. Now webpack is adding the Meteor polyfill instead.
