### ISSUE TITLE
How to delete react-redbox from the project?

### ISSUE THREAD

**Issue by tommyJS** [thereactivestack/kickstart-simple#24]
Hi @eXon ,

I want to delete this red error message when I have an error and I deleted: `"redbox-react": "^1.1.1"` from `webpack.packages.json`, then I deleted also `node_modules` folder and executed `meteor` once again. Unfortunately, `redbox-react` is still in `node_modules`.

What should I do then?

**Comment by Masaki42** [comment]
Have you tried remove it from '/entry/client/webpack.conf.js'?

**Comment by eXon** [comment]
You should be able to remove redbox-react. It is not required in any way.
