### ISSUE TITLE
SSR in product only?

### ISSUE THREAD

**Issue by SachaG** [thereactivestack/kickstart-simple#28]
I'm pretty new to the whole Webpack/React stack so sorry in advance if this is obvious, but is there any specific reason why SSR is limited to production mode? Just curious to know :)

**Comment by eXon** [comment]
It's simply because you cannot have SSR AND hot reloading (without page refresh) at the same time. It would be a deal breaker to not have it :)

**Comment by SachaG** [comment]
That makes sense, thanks :)
