### ISSUE TITLE
Issues with FlowRouter

### ISSUE THREAD

**Issue by hyperh** [thereactivestack/kickstart-simple#30]
Anyone manage to get this working with FlowRouter and ReactLayout? 

I keep getting `There is no route for the path: /`, so I tried to put this in `entry/client/routes.jsx`
````
import TodoApp from 'TodoApp/client/TodoApp';
import TodoMain from 'TodoApp/client/TodoMain';
import Test from 'TodoApp/client/components/Test';

// Tell FR to wait until our ES6 code is fully initialized
FlowRouter.wait();

FlowRouter.route('/', {
  name: "home",
  action() {
    ReactLayout.render(TodoApp, { children: <TodoMain />});
  }
});

// FlowRouter is now ready to go
FlowRouter.initialize();

FlowRouter.go("/");
````

and I get `Uncaught Error: can't wait after FlowRouter has been initialized`

**Comment by tomitrescak** [comment]
There is a [kicktart-flowrouter](https://github.com/thereactivestack/kickstart-flowrouter) package so you should check it out.

Otherwise, make sure that `FlowRouter.wait();` is in the client.startup.js file.

**Comment by hyperh** [comment]
Thanks! I'll check that out.

Also where is the `client.startup.js` file supposed to go in the file structure?
