### ISSUE TITLE
Server files not reloaded when using Typescript

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-simple#31]
Hi, once again, thanks for all the great work!

I have a TS related problem. When I modify a server file it correctly triggers the server restart, yet it does not trigger a webpack rebuild. This is only happening with ".ts" or ".tsx" files. I thought that this were added to the list of watched files. On client all works peachy!

Thanks!

**Comment by tomitrescak** [comment]
As you see in this gif, changing files trigger server reload, but changes are not reflected. The only way to force server file relaod is to modify webpack server files ;/

![webpack2](https://cloud.githubusercontent.com/assets/2682705/11683038/ab142366-9e68-11e5-9c75-007467aea5b8.gif)

**Comment by eXon** [comment]
I'm not sure I understand what happened here. ts and tsx extensions are still watched by the plugin. Do you have the same problem with js and jsx?

**Comment by tomitrescak** [comment]
@eXon The js and jsx are behaving well as you see in the GIF below. I have crated a minimally reproducible app, which you can find here [https://github.com/tomitrescak/kickstart-flowrouter/tree/typescript](https://github.com/tomitrescak/kickstart-flowrouter/tree/typescript)

![webpacktsjs](https://cloud.githubusercontent.com/assets/2682705/11807706/d303d8dc-a31b-11e5-88da-3332238f299a.gif)

If you use the app, please note that you have to use the http://localhost:3000/todo route to display the todo app. I have tried anything and everything to get it working, but am still down to modfying webpack.conf.js to get the server changes working in ts files.

**Comment by tomitrescak** [comment]
On thing I've noticed is that when I modify JS files the changes are reflected immediatelly, but it does not rebuild TS files. In following setup:

1. I modify TS file to display "TS OK"
2. Nothing happens
3. I modify JS file to display "JS OK"
4. Server now displays "JS OK" but does not display "TS OK"
5. I modify "webpack.conf.js"
6. Server now displays "TS OK" and "JS OK"

**Comment by D1no** [comment]
Just stumbled over this. I don't have this problem. I use ts-loader and my conf looks like the following. Maybe you should also use babels loose-mode, like TypeScript does?

entry/client/webpack.conf.js
```js
module.exports = {
  entry: './entry',
  plugins: plugins,
  module: {
    loaders: [
      { test: /\.ts(x?)$/, loader: 'babel?loose=all!ts-loader' },
      { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
      { test: /\.css$/, loader: cssLoader },
      { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
      { test: /\.(svg|ttf|woff|eot)(\?.*)?$/, loader: 'file' }
    ]
  },
  ts: {
    configFileName: "../../../tsconfig.json",
    transpileOnly: true
  }
};
```

entry/webpack.conf.js
```js
  devServer: {
    // You can change this to your server IP address to access it remotely
    host: 'localhost'
  },
  hotMiddleware: {
    reload: true
  },
  resolve: {
    root: path.join(__dirname, '..', 'modules'),
    extensions: ['', '.js', '.jsx', '.json', '.css', '.scss', ".ts", ".tsx"]
  }
};
```

tsconfig.json
```json
{
  "compilerOptions": {
    "target": "ES6",
    "jsx": "react",
    "sourceMap": true,
    "experimentalDecorators": true,
    "module": "commonjs"
  },
  "exclude": [
      "node_modules",
      ".meteor"
  ]
}
```

Could also be that you missed to pass on source maps... anyhow - hope it helps.

**Comment by sayawan** [comment]
same behavior for JS files, too

**Comment by tomitrescak** [comment]
@D1no the problem is on server, not on client ;(

**Comment by tomitrescak** [comment]
OK, changing the loader to ts-loader solved the problem. 
Here is the working config for Babel 6:


```javascript
// server/webpack.conf.js
var webpack = require('webpack');

var babelSettings = { presets: ['react', 'es2015', 'stage-0'] };
babelSettings.plugins = ['transform-decorators-legacy'];

module.exports = {
  entry: './entry',
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'babel?' + JSON.stringify(babelSettings) + '!ts', exclude: /node_modules|lib/ },
      { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
      { test: /\.css$/, loader: 'null' },
      { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
      { test: /\.(svg|ttf|woff2?|eot)(\?.*)?$/, loader: 'file' }
    ]
  }
};
```

```javascript
// client/webpack.conf.js
var webpack = require('webpack');

var babelSettings = { presets: ['react', 'es2015', 'stage-0'] };
babelSettings.plugins = ['transform-decorators-legacy'];

if (process.env.NODE_ENV !== 'production' && !process.env.IS_MIRROR) {
  babelSettings.plugins.push(['react-transform', {
    transforms: [{
      transform: 'react-transform-hmr',
      imports: ['react'],
      locals: ['module']
    }, {
      transform: 'react-transform-catch-errors',
      imports: ['react', 'redbox-react']
    }]
    // redbox-react is breaking the line numbers :-(
    // you might want to disable it
  }]);
}

module.exports = {
  entry: './entry',
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'babel?' + JSON.stringify(babelSettings) + '!jstransform-loader?jsx-control-statements/jstransform!ts', exclude: /node_modules|lib/ },
      { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
      { test: /\.css$/, loader: 'style!css' },
      { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
      { test: /\.(svg|ttf|woff2?|eot)(\?.*)?$/, loader: 'file' }
    ]
  }
};
```

```javascript
// webpack.conf.js
var webpack = require('webpack');

var babelSettings = { presets: ['react', 'es2015', 'stage-0'] };
babelSettings.plugins = ['transform-decorators-legacy'];

module.exports = {
  entry: './entry',
  module: {
    loaders: [
      { test: /\.tsx?$/, loader: 'babel?' + JSON.stringify(babelSettings) + '!ts', exclude: /node_modules|lib/ },
      { test: /\.jsx?$/, loader: 'babel', query: babelSettings, exclude: /node_modules/ },
      { test: /\.css$/, loader: 'null' },
      { test: /\.(png|jpe?g)(\?.*)?$/, loader: 'url?limit=8182' },
      { test: /\.(svg|ttf|woff2?|eot)(\?.*)?$/, loader: 'file' }
    ]
  }
};
```
