### ISSUE TITLE
Meteor, $ and other "globals"

### ISSUE THREAD

**Issue by vonwao** [thereactivestack/kickstart-simple#32]
When I try to use the kickstart project, I'm get some errors, like:

both.jsx:15 Uncaught TypeError: $ is not a function
VM1310:9 Uncaught ReferenceError: Meteor is not defined

I'm not sure why Meteor isn't working, because it's used in other components in the example, but I'm guessing $ is jquery that's not in the global scope.  Also having an issue with another "global" from my custom meteor package.  

I may be missing something obvious but I'm wondering if there's a way to inject things into the global scope?

**Comment by vonwao** [comment]
Also, how do import something that's exported from a Meteor package?  

Also, I realize the general pattern is to avoid globals, but at the same time sometimes you need to, and as long as globals are declared somewhere explicitly, I can't see a downside.

**Comment by eXon** [comment]
You can access any global variable inside your code. This is not a problem.

To make sure we don't have two jQuery, we have to tell Webpack that the jquery module is the global variable $ (it's totally normal).

All you need is to add your module to the externals (see https://github.com/thereactivestack/kickstart-simple/blob/master/entry/webpack.conf.js). 

This means import $ from 'jquery' will point to your global $.

Have you removed jquery package from your project?

**Comment by vonwao** [comment]
Ok, understood.  I do see the externals, and Jquery is in there, I did not remove it.  Not sure why I'm getting error: $ is not a function.  I will keep trying some things.

Also wonder why "Meteor is not defined"

Thanks.

**Comment by eXon** [comment]
Do you have a git I can clone an example of the issue?

**Comment by pors** [comment]
Not sure where I should ask this, but since the externals are mentioned here: why did you choose to use the Meteor-provided React, jQuery etc. and not including them through webpack.packages.json?

It seems to me that the latter gives you more flexibility, but probably there is a disadvantage?

**Comment by eXon** [comment]
@pors There is a few packages that you want to use with Meteor instead of NPM, but very few.

The reason is if you are using a Meteor package, it will not be able to see the NPM modules (until Meteor 1.3 at least). When you set the external, you tell Webpack: "hey, use this global variable when I import this module".

If you want ReactMeteorData mixin to work, it has to use the Meteor version. If you want react-router-ssr pacakge, it needs react-router from Meteor too.

This will be A LOT simplier very soon. It will automatically detect the externals all the packages are exposing and you will not need to specify it. Much more coming soon :)

**Comment by eXon** [comment]
Since Meteor package webpack:webpack 0.4.0, all your global variables exported by packages are exposed to import. You don't need to specify externals manually :)

**Comment by pors** [comment]
@eXon thanks for the explanation. I think ReactMeteorData will work with an external (non-meteor) React as well. It does for me so far.

**Comment by pors** [comment]
About webpack:webpack 0.4.0: that's great! I see you already updated kickstart-simple :)

**Comment by eXon** [comment]
You can import it like this :) (I forgot to give an example here, just for sake of clarity!)

```javascript
import ReactMeteorData from 'react-meteor-data';
```
