### ISSUE TITLE
Dev dependencies

### ISSUE THREAD

**Issue by dagatsoin** [thereactivestack/kickstart-simple#39]
How do you specify dev dependencies in the `webpack.packages.json`?

I want to use `npm install --save-dev redux-devtools` as stated in [rackt/redux readme](https://github.com/rackt/redux).

**Comment by eXon** [comment]
You don't need to use dev dependencies. Just add them to webpack.packages.json. They are not going to be bundled with your app if they are not used in production. You can use: `if (process.NODE_ENV === 'production')` to know that.

In the meteor-webpack 1.0, we'll use a regular package.json so you'll be able to use them :)
