### ISSUE TITLE
React from NPM

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/kickstart-simple#43]
Just a quick question. Why are we using React packed by Meteor and not the native version from NPM? Thanks!

**Comment by eXon** [comment]
You can use the NPM version but you loose ReactMeteorData and react-router-ssr. Meteor 1.3 will let us use the NPM version within Meteor package but for now we have to deal with it :(.

**Comment by tomitrescak** [comment]
Hmm, I tried removing it, but it says "React not found" ... since I use mantra I do not need neither of those two. any advice?

**Comment by tomitrescak** [comment]
Ah .. Meteor 1.3
Got it ;)
