### ISSUE TITLE
Meteor.call leads to Method not found [404]

### ISSUE THREAD

**Issue by panw** [thereactivestack/kickstart-simple#47]
I used this starter code, but moved the methods within /server. When I try to do Meteor.call('someMethod') it results in `Method not found [404]`.

Below are the snippets of code and its location. Please let me know if something is off. Thanks
/server
```js
Meteor.methods({
	hello() {
		console.log('Hello Method');
	}
});
```
/client/components/
```js
Meteor.call('hello');
```

**Comment by tomitrescak** [comment]
@panw ... you need to go over Meteor basics first. Please read well Meteor articles about the architecture of Meteor application. Whatever you put inside server folder does not exist on client ... therefore client does not know about your method alas your error.

**Comment by eXon** [comment]
You need to make sure your file is imported somewhere within the server entry file (`entry/server/index.js`).
