### ISSUE TITLE
npm installed in local

### ISSUE THREAD

**Issue by ecomotto6user** [thereactivestack/kickstart-simple#48]
I am using Node v5.0.0 and npm v3.3.6 on my Mac machine. Every time I run the kickstart project, webpack downloads npm v.2.14.15 to local and I couldn't understand why this behavior happens. Is there any config to tell webpack to use global npm?

**Comment by eXon** [comment]
With meteor-webpack 1.0, it will let you run your npm install by yourself :) It will be released march 1st.
