### ISSUE TITLE
package.json instead of packages.json

### ISSUE THREAD

**Issue by mist123** [thereactivestack/kickstart-simple#6]
Hi! Good work!
I'm wondered why can't we use [package.json](https://docs.npmjs.com/files/package.json) instead of inventing packages.json?

**Comment by tomitrescak** [comment]
That's used by meteor's package that enables NPM use.

**Comment by eXon** [comment]
This is using meteorhacks:npm package. It is to make sure their is no conflict with a regular NPM package.json file. (I don't thin it should happen anyway)
