### ISSUE TITLE
Erro on Chrome

### ISSUE THREAD

**Issue by SenerDemiral** [thereactivestack/kickstart-simple#7]
Chrome: Uncaught SyntaxError: Unexpected token ) webpack-reload.js :30
But Firefox running.!

Cloned 10min ago.

**Comment by eXon** [comment]
This is weird. I will need more infos to replicate. Do you have the latest webpack:webpack package?

**Comment by SenerDemiral** [comment]
Yes, webpack 0.1.6

**Comment by eXon** [comment]
What is your Chrome version? I think I forgot to add the ecmascript transpiler and my version was probably supporting more features.

**Comment by SenerDemiral** [comment]
its working on Phone (Chrome)
On windows deksktop Chrome and Firefox are not working.

**Comment by SenerDemiral** [comment]
Chromium Version 44.0.2403.89 Ubuntu 14.04 (64-bit)

**Comment by SenerDemiral** [comment]
I do not know but Windows versions (Chrome and Firefox) start to work,
But linux Chromium not yet!

**Comment by SenerDemiral** [comment]
Chromium was working before webpack 0.1.6

**Comment by eXon** [comment]
On Mac it's working for me. Can you try 0.1.7 and let me know if it fix the problem?

**Comment by SenerDemiral** [comment]
OK, I try to install Chrome update

**Comment by SenerDemiral** [comment]
Yesss, its working now.

**Comment by eXon** [comment]
Awesmoe. Shouldn't happen anymore. Thx for reporting!
