### ISSUE TITLE
Meteor.users is not a Mongo.Collection - breaks jagi:astronomy

### ISSUE THREAD

**Issue by jbbr** [thereactivestack/kickstart-simple#8]
I'm using https://github.com/jagi/meteor-astronomy to add schemas to my Meteor collections.

When using this stack (And only this - with the skeleton of @jedwards1211 I don't have this problem), the package does not work properly with Meteor.users anymore.

It seems as if "Meteor.users" is not an instance of "Mongo.Collection" when using your stack:

```js
expect(Meteor.users instanceof Mongo.Collection).toBe(true)
```

This fails when using your stack but is true when using plain meteor

This might break also other Meteor packages

**Comment by eXon** [comment]
This is weird. I'll take a look at it when I have a few minutes.

**Comment by jbbr** [comment]
Ugly workaround: 

```js
Meteor.users.__proto__ = Mongo.Collection.prototype;
```

**Comment by eXon** [comment]
I'm not touching the Meteor.users or even the Meteor object. This is probably a side-effect from something else. Do you have the same problem on the client and on the server?

**Comment by eXon** [comment]
Do you have this problem on production or also in development?

**Comment by jbbr** [comment]
Haven't tried production yet. It's happening in development - in a clean clone of kickstart-simple

**Comment by jbbr** [comment]
But this into `app/main/server/entry.js`:
```js
console.log( Meteor.users instanceof Mongo.Collection );
```
output: false

same in a freshly created meteor project in server/: true

**Comment by jbbr** [comment]
Okay: The output is _false_ on a fresh meteor project (meteor create) - but only because Meteor.users is undefined. After adding `accounts-password` it's true.

**Comment by eXon** [comment]
This bug has been fixed. SSR was replacing Mongo.Collection with a proxy class. Now it just patch the real one.

`meteor update reactrouter:react-router-ssr`
